---
# ===================================================================
# RUNTIME-TIME CONFIG PROPERTIES
#
# This is multi-env properties file. Keep sensitive data in external
# file that SysOps can source at runtime.
# ===================================================================


# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# Server
server:
  port: 8443
  ssl:
    key:
    cert:
    ca:
    requestCert: true,
    rejectUnauthorized: fals
  debug:
    hose: localhost
    ssl:
      passphrase:
      keyFile: USER_HOME/.ssh/server.pem
      certFile: USER_HOME/.ssh/server.crt
      caFile: USER_HOME/.ssh/ca.crt
  release:
    hose: mydomain.com
    ssl:
      passphrase:
#      keyFile: SERVER_HOME/.ssh/server.pem
#      certFile: SERVER_HOME/.ssh/server.pem
#      caFile: SERVER_HOME/.ssh/ca.crt

# Raw Keys
secret:
  privateKey:
  publicKey:
  debug:
    privateKeyFile: USER_HOME/.ssh/auth.rsa  # set paths to your rsa files
    publicKeyFile: USER_HOME/.ssh/auth.rsa.pub
    sharedSecret: "my dev shared secret"
  release:
#    privateKeyFile: SERVER_HOME/.ssh/auth.rsa
#    publicKeyFile: SERVER_HOME/.ssh/auth.rsa.pub
    sharedSecret: "my prod shared secret"

# koa-jwt options
jwt:
  algorithm: RS256
  issuer: http://localhost:8080/auth
  audience:
    - http://localhost:8080/api/v1/users
    - http://localhost:8080/api/v1/providers
  debug:
    expiresInMinutes: 10
  release:
    expiresInMinutes: 30


# bcrypt
bcrypt:
  saltWorkFactor: 8

# login
login:
  maxLoginAttempts: 5
  lockTime: 60000 #7200000
