---
# ===================================================================
# RUNTIME-TIME CONFIG PROPERTIES
#
# This is multi-env properties file. Keep sensitive data in external
# file that SysOps can source at runtime.
# ===================================================================


# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# Server
server:
  port: 8080

# Raw Keys
secret:
  privateKey:
  publicKey:
  debug:
    privateKeyPath: USER_HOME/.ssh/auth.rsa  # set paths to your rsa files
    publicKeyPath: USER_HOME/.ssh/auth.rsa.pub
    sharedSecret: "my dev shared secret"
  release:
#    privateKeyPath: SERVER_HOME/.ssh/auth.rsa
#    publicKeyPath: SERVER_HOME/.ssh/auth.rsa.pub
    sharedSecret: "my prod shared secret"

# koa-jwt options
jwt:
  algorithm: RS256
  issuer: http://localhost:8080/auth
  audience:
    - http://localhost:8080/api/v1/users
    - http://localhost:8080/api/v1/providers
  debug:
    expiresInMinutes: 10
  release:
    expiresInMinutes: 30


# bcrypt
bcrypt:
  saltWorkFactor: 8
