---
# ===================================================================
# RUNTIME-TIME CONFIG PROPERTIES
#
# This is multi-env config system. Keep sensitive data in external
# file that SysOps can source at runtime.
# ===================================================================


# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# Server
server:
  options:
  ssl:
    options:
      key:
      cert:
      requestCert: true,
      rejectUnauthorized: false
    files:
      key:
      cert:

# mongodb
mongo:
  uri: localhost/authDB
  options:

# jwt
jwt:
  privateKey:
  publicKey:
  privateKeyFile: ~/.ssh/auth.rsa
  publicKeyFile: ~/.ssh/auth.rsa.pub
  # koa-jwt options
  options:
    algorithm: RS256
    issuer:
    audience:
      - http://localhost:8080/api/v1/users
      - http://localhost:8080/api/v1/providers
    expiresInMinutes: 30

# bcrypt
bcrypt:
  saltWorkFactor: 8

# login
login:
  maxLoginAttempts: 5
  lockTime: 7200000
